# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

apt_packages:
  - p7zip-full
  - libxml2-dev
warnings_are_errors: false
env:
  global:
    - ZIP_CALL="7z a %s.7z %s"
    - UNZIP_CALL="7z e %s.7z"
    
after_success:
  - Rscript -e 'pkgdown::build_site()'

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_PAT
  keep-history: true
  local-dir: docs
  on:
    branch: master